steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west2-docker.pkg.dev/project-1-509015/gke-repo/quickstart-image', './App1' ]
  id: 'Build Docker Image'

  

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west2-docker.pkg.dev/project-1-509015/gke-repo/quickstart-image' ]
  id: 'Push Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west2-docker.pkg.dev/project-1-509015/gke-repo/flask-image', './App2' ]
  id: 'Build Docker Image2'

 

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west2-docker.pkg.dev/project-1-509015/gke-repo/flask-image' ]
  id: 'Push Docker Image2'


- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=europe-west2
    gcloud deploy apply --file deploy/dev.yaml --region=europe-west2
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=europe-west2 --skaffold-file=skaffold.yaml


options:
  logging: CLOUD_LOGGING_ONLY




