apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/project-1-509015/locations/europe-west2-a/clusters/gke-1
